# Generated by Django 5.0.3 on 2024-03-24 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction_listing_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
