# Generated by Django 5.0.3 on 2024-03-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_auction_alter_auction_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidd', to='auctions.bid'),
        ),
    ]
