# Generated by Django 5.0.3 on 2024-03-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listing_price_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.bid'),
        ),
    ]
